name: Build and Deploy to YC

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'AuthMicroservice/**'
env:
  SERVICE_NAME: auth-service

jobs:
  build-and-push-to-ycr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to YC Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/${{ env.SERVICE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
      - name: Build & Push (auth-service â†’ YCR)
        uses: docker/build-push-action@v5
        with:
          context: ./AuthMicroservice
          file: ./AuthMicroservice/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max