name: Build and Deploy to YC

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'AuthMicroservice/**'
env:
  SERVICE_NAME: auth-service

jobs:
  build-and-push-to-ycr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to YC Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Build Docker image
        run: |
          docker build \
          -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/auth-service:latest \
          -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/auth-service:${{ github.sha }} \
          ./AuthMicroservice

          - name: Push Docker image
            run: |
              docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/auth-service:latest
              docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/auth-service:${{ github.sha }}